import { ScenePlayer } from './scene-engine.js';
const $=s=>document.querySelector(s);
const make=(tag,attrs={},text)=>{const e=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(v===undefined||v===null)continue;if(k==='class')e.className=v;else e.setAttribute(k,v);}if(text!==undefined)e.textContent=text;return e;};
const snapshot=window.TEACHING_SNAPSHOT||null;
const state={offline:!!snapshot,token:'',learner:'default',document:null,storyboard:null,edition:'',editions:[],progress:{},sceneStates:{},player:null,activeScene:null,activeSection:null,mode:'experiment',route:0,saveChain:Promise.resolve(),lastSaved:'',collection:'',library:[],libraryResponse:{},query:'',kind:'',notes:[],connections:null};
const safeStore={get:key=>{try{return localStorage.getItem(key);}catch{return null;}},set:(key,value)=>{try{localStorage.setItem(key,value);}catch{}}};
const visualThemes=['lamplight','aperture','margin'];
function applyVisualTheme(value){const theme=visualThemes.includes(value)?value:'lamplight';document.documentElement.dataset.theme=theme;const choice=$('#theme-select');if(choice)choice.value=theme;}
applyVisualTheme(safeStore.get('lucerna-visual-theme/v1'));
$('#theme-select')?.addEventListener('change',event=>{applyVisualTheme(event.target.value);safeStore.set('lucerna-visual-theme/v1',event.target.value);});
window.addEventListener('storage',event=>{if(event.key==='lucerna-visual-theme/v1')applyVisualTheme(event.newValue);});
function notice(message,error=false){$('#save-status').textContent=message;$('#save-status').style.color=error?'var(--error)':'var(--muted)';}
function params(extra={}){const q=new URLSearchParams({learner_id:state.learner,...extra});for(const[k,v]of q)if(v==='undefined'||v==='null'||v==='')q.delete(k);return q.toString();}
function docParams(extra={}){return params({edition_id:state.edition,...extra});}
async function api(path,body,method='POST'){if(state.offline)throw new Error('This exported exploration does not connect to the learning workspace.');const options=body===undefined?{}:{method,headers:{'Content-Type':'application/json','X-Teaching-Token':state.token},body:JSON.stringify(body)};let response;try{response=await fetch(path,options);}catch{throw new Error('The local workspace is not responding. Restart Lucerna and retry. Your saved sources remain in the workspace.');}const data=await response.json().catch(()=>({error:'Request failed ('+response.status+').'}));if(!response.ok)throw new Error(typeof data.error==='string'?data.error:data.error?.message||data.message||'Request failed ('+response.status+').');return data;}
function routeLink(id,section,scene,extra={}){const q=new URLSearchParams({document:id,learner:state.learner,...(section?{section}:{}),...(scene?{scene}:{}),...(state.edition?{edition:state.edition}:{}),...extra});for(const[k,v]of q)if(v===''||v===undefined||v===null)q.delete(k);return'#'+q;}
function externalURL(raw){if(typeof raw!=='string'||!/^https?:\/\//i.test(raw.trim()))return null;try{const u=new URL(raw.trim());return['http:','https:'].includes(u.protocol)?u.href:null;}catch{return null;}}
function extLink(label,url){return make('a',{href:url,target:'_blank',rel:'noopener noreferrer'},label);}
function sourceURL(block){const source=state.document?.source||{},pdf=source.format==='pdf'||source.kind==='pdf';let raw=externalURL((pdf?source.download_url:null)||source.content_url||source.canonical_url||source.original);if(pdf&&!state.offline&&source.cache_path)raw='/api/documents/'+encodeURIComponent(state.document.id)+'/source';if(!raw)return null;const u=new URL(raw,window.location.href);if(block?.anchor?.fragment&&!pdf)u.hash=block.anchor.fragment;else if(block?.anchor?.page&&pdf&&(raw.startsWith('/api/documents/')||/\/pdf\/|\.pdf(?:$|[?#])/i.test(raw)))u.hash='page='+block.anchor.page;return u.href;}
function clear(e){e.replaceChildren();}
function destroyPlayer(){if(state.player){state.player.destroy();state.player=null;}}
function loading(text='Opening the source and its explanation…'){const p=make('div',{class:'loading'});p.append(make('span',{class:'loading-lens','aria-hidden':'true'}),document.createTextNode(text));return p;}
function sourceBlock(id){for(const section of state.document?.sections||[]){const block=(section.blocks||[]).find(b=>b.id===id);if(block)return{block,section};}return null;}
function showSource(id){const found=sourceBlock(id);if(!found)return;window.location.hash=routeLink(state.document.id,found.section.id,state.activeScene?.id,{mode:'read',anchor:id});}
async function copy(text,feedback){try{await navigator.clipboard.writeText(text);feedback.textContent='Copied with the current source and experiment settings. Paste it into your teaching conversation.';}catch{const area=make('textarea',{'aria-label':'Context to copy',rows:7});area.value=text;feedback.replaceChildren(make('p',{},'Select and copy this context:'),area);area.select();}}
function contextText(question){const d=state.document,s=state.activeSection,c=state.activeScene;return'Continue with Lucerna in the saved workspace.\nLearner: '+state.learner+'\n'+(d?'Document: '+d.title+' ['+d.id+']\nSource: '+(d.source?.canonical_url||d.source?.original||'Imported source')+'\nSection: '+(s?.title||'')+' ['+(s?.id||'')+']\nScene: '+(c?.title||'')+' ['+(c?.id||'')+']\nEdition: '+(state.edition||'default')+'\nParameters: '+JSON.stringify(state.player?.state().parameters||{})+'\n':'')+'Question: '+question+'\nRead the source and my saved learning context. Explain the missing connection, revise the exploration when useful, and complete any saved request with your response.';}
function questionBox(initial='',kind='explain',context={}){
 const box=make('section',{class:'question-box'});box.append(make('h3',{},'Follow the question.'),make('p',{},state.offline?'Bring the source and experiment back into your teaching conversation.':'Save this question with its exact source and settings. Your teaching agent can pick it up in your conversation.'));
 const input=make('textarea',{rows:3,'aria-label':'Question for your teaching agent',placeholder:'What happens if…? Why does this step follow? Connect this to…'});input.value=initial;box.append(input);
 const actions=make('div',{class:'actions'}),feedback=make('div',{class:'question-feedback',role:'status'}),copyButton=make('button',{type:'button'},'Copy to my conversation');copyButton.onclick=()=>copy(contextText(input.value.trim()),feedback);
 if(!state.offline){const save=make('button',{type:'button',class:'primary'},'Save question');save.onclick=async()=>{if(!input.value.trim()){feedback.textContent='Write the question you want to explore.';input.focus();return;}save.disabled=true;try{const saved=await api('/api/requests',{learner_id:state.learner,edition_id:state.document?state.edition||undefined:undefined,kind,document_id:state.document?.id,section_id:state.activeSection?.id,scene_id:state.activeScene?.id,question:input.value.trim(),context,parameters:state.player?.state().parameters||{}});feedback.textContent='Saved for your agent. Bring it into your conversation to pick it up now. Request '+saved.id+'.';}catch(e){feedback.textContent=e.message;}finally{save.disabled=false;}};actions.append(save);}
 actions.append(copyButton);if(!state.offline){const inbox=make('button',{type:'button',class:'quiet'},'View replies');inbox.onclick=()=>openQuestions();actions.append(inbox);}box.append(actions,feedback);return box;
}
function simpleDialog(title,build){const d=make('dialog',{class:'collection-dialog'}),head=make('div',{class:'dialog-heading'}),close=make('button',{type:'button',class:'icon-button','aria-label':'Close dialog'},'×');head.append(make('h2',{},title),close);d.append(head);close.onclick=()=>d.close();d.addEventListener('close',()=>d.remove());document.body.append(d);build(d);d.showModal();return d;}
function newCollection(documentId){simpleDialog(documentId?'Keep this source together.':'Make a collection.',dialog=>{const form=make('form'),label=make('label',{for:'collection-title'},'Collection title'),input=make('input',{id:'collection-title',required:'',placeholder:'A question, a subject, a project…'}),error=make('p',{class:'inline-error',hidden:'',role:'alert'}),button=make('button',{class:'primary'},'Create collection');form.append(label,input,error,make('div',{class:'actions'}));form.lastChild.append(button);form.onsubmit=async e=>{e.preventDefault();button.disabled=true;try{await api('/api/collections',{learner_id:state.learner,title:input.value.trim(),document_ids:documentId?[documentId]:[]});dialog.close();notice('Collection created.');if(!state.document)library();}catch(err){error.hidden=false;error.textContent=err.message;button.disabled=false;}};dialog.append(form);});}
async function addToCollection(){const response=await api('/api/collections?'+params());simpleDialog('Add to a collection',dialog=>{const select=make('select',{'aria-label':'Collection'});for(const c of response.items||[])select.append(make('option',{value:c.id},c.title));const actions=make('div',{class:'actions'}),add=make('button',{type:'button',class:'primary'},'Add source'),create=make('button',{type:'button'},'New collection');add.disabled=!response.items?.length;add.onclick=async()=>{const c=response.items.find(x=>x.id===select.value);if(!c)return;try{await api('/api/collections/'+encodeURIComponent(c.id),{learner_id:state.learner,document_ids:[...new Set([...(c.document_ids||[]),state.document.id])]},'PUT');dialog.close();notice('Source added to '+c.title+'.');}catch(e){dialog.append(make('p',{class:'inline-error'},e.message));}};create.onclick=()=>{dialog.close();newCollection(state.document.id);};actions.append(add,create);dialog.append(select,actions);});}
let librarySearchTimer;
async function library(){
 destroyPlayer();state.document=null;state.activeSection=null;state.activeScene=null;state.edition='';const turn=state.route,main=$('#main');clear(main);
 const page=make('div',{class:'page'}),hero=make('section',{class:'library-hero'}),intro=make('div');intro.append(make('p',{class:'eyebrow'},'THE LIBRARY'),make('h1',{},'Make room for\na deeper understanding.'),make('p',{class:'intro'},'Find the idea. Open the source. Turn the difficult part into something you can work with.'));
 const aside=make('aside',{class:'library-aside'});aside.append(make('p',{},'A paper becomes more useful when its ideas have somewhere to connect.'));const path=make('a',{href:'#pathways',class:'text-button'},'Continue a learning path →');aside.append(path);hero.append(intro,aside);page.append(hero);const showcase=make('details',{class:'showcase-section'});showcase.append(make('summary',{},'Open a working lab'));const labShelf=make('div',{class:'showcase-shelf'});showcase.append(labShelf);page.append(showcase);showcase.hidden=true;api('/api/showcases').then(response=>{const labs=Array.isArray(response)?response:response.items||[];if(!labs.length||turn!==state.route)return;showcase.hidden=false;for(const lab of labs){const card=make('article',{class:'showcase-card'});card.append(make('p',{class:'eyebrow'},'AN EXPLORABLE LAB'),make('h3',{},lab.title),make('p',{},lab.description||''));const launch=make('button',{type:'button',class:'text-button'},'Open lab'+(lab.scene_count?' · '+lab.scene_count+' scenes':'')+' →');launch.onclick=async()=>{launch.disabled=true;launch.textContent='Opening the lab…';try{const installed=await api('/api/showcases',{slug:lab.id||lab.slug,learner_id:state.learner});window.location.hash=routeLink(installed.document_id||installed.id,null,null,{edition:'default'});}catch(e){notice(e.message,true);launch.disabled=false;launch.textContent='Retry opening lab →';}};card.append(launch);labShelf.append(card);}if(!state.query&&!state.libraryResponse.total)showcase.open=true;}).catch(()=>{});
 const toolbar=make('div',{class:'library-toolbar'}),search=make('div',{class:'library-search'}),label=make('label',{for:'library-query'},'Search the full text of your sources'),input=make('input',{id:'library-query',type:'search',placeholder:'A concept, a claim, a phrase…',autocomplete:'off'});input.value=state.query;search.append(label,input);
 const filters=make('div',{class:'filter-tools'}),kind=make('select',{'aria-label':'Source kind'});for(const[value,text]of [['','All sources'],['paper','Papers'],['lesson','Lessons'],['visual-aid','Visual aids']])kind.append(make('option',{value},text));kind.value=state.kind;const add=make('button',{type:'button',class:'quiet'},'+ Collection');add.onclick=()=>newCollection();filters.append(kind,add);toolbar.append(search,filters);page.append(toolbar);
 const collections=make('div',{class:'collection-strip','aria-label':'Collections'}),summary=make('div',{class:'library-summary'}),results=make('div');page.append(collections,summary,results);main.append(page);
 let searchSerial=0;
 const update=async()=>{const serial=++searchSerial;state.query=input.value.trim();state.kind=kind.value;results.replaceChildren(loading(state.query?'Searching across the source text…':'Opening your library…'));try{
  const response=state.query?await api('/api/search?'+params({q:state.query,collection_id:state.collection,kind:state.kind,limit:60})):await api('/api/library?'+params({kind:state.kind,collection_id:state.collection}));if(turn!==state.route||serial!==searchSerial)return;clear(results);
  summary.replaceChildren(make('span',{},state.query?(response.total??response.items?.length??0)+' passages · '+(response.mode==='fts5'?'full-text index':'text search'):(response.total??response.items?.length??0)+' sources'),make('span',{},state.query?'SOURCE-ANCHORED RESULTS':'YOUR LOCAL COLLECTION'));
  if(state.query){results.className='search-results';for(const hit of response.items||[]){const item=make('article',{class:'search-result'}),a=make('a',{href:routeLink(hit.document_id,hit.section_id,null,{mode:'read',anchor:hit.block_id||''})});a.append(make('span',{class:'section-label'},hit.section_title||'Source match'),make('h3',{},hit.title));item.append(a,make('p',{},hit.snippet||hit.text||''));results.append(item);}}
  else{state.library=response.items||[];state.libraryResponse=response;showcase.open=(response.total??state.library.length)===0;results.className='library-list';for(const d of state.library){const item=make('article',{class:'library-item'+(d.has_storyboard?' has-scenes':'')}),top=make('div',{class:'item-top'});top.append(make('span',{class:'tag'},(d.source_format||d.kind||'Source')+(d.version?' · v'+d.version:'')));if(d.has_storyboard)top.append(make('span',{class:'scene-badge'},'◌ Explorable'));item.append(top);const heading=make('h3');heading.append(make('a',{href:routeLink(d.id)},d.title));item.append(heading,make('p',{},d.summary||'Open the source and follow its ideas.'),make('div',{class:'item-meta'},[d.authors?.slice(0,2).join(', '),d.section_count?d.section_count+' sections':''].filter(Boolean).join(' · ')),make('a',{href:routeLink(d.id),class:'open-source'},d.has_storyboard?'Enter the exploration →':'Open the source →'));results.append(item);}}
  if(!response.items?.length){results.className='';const empty=make('section',{class:'empty'});empty.append(make('h2',{},state.query?'Nothing matches that phrase yet.':'Your next connection starts here.'),make('p',{},state.query?'Try a shorter phrase or a related concept. Search looks through the source text in your library.':'Add a paper, book, chapter, or passage. Your teaching agent can turn it into an exploration shaped around what you want to understand.'));if(!state.query){const b=make('button',{type:'button',class:'primary'},'Add your first source');b.onclick=openImport;empty.append(b);}results.append(empty);}
 }catch(e){results.replaceChildren(make('p',{class:'inline-error'},e.message));}};
 const list=await api('/api/collections?'+params()).catch(()=>({items:[]}));if(turn!==state.route)return;const all=make('button',{type:'button',class:state.collection?'':'active'},'All sources');all.onclick=()=>{state.collection='';library();};collections.append(all);for(const c of list.items||[]){const b=make('button',{type:'button',class:state.collection===c.id?'active':''},c.title+' ('+(c.count??c.document_ids?.length??0)+')');b.onclick=()=>{state.collection=c.id;library();};collections.append(b);}input.oninput=()=>{clearTimeout(librarySearchTimer);librarySearchTimer=setTimeout(update,260);};kind.onchange=update;await update();
}
function progressKey(){return'lucerna.explorer.'+(state.document?.id||'')+'.'+state.learner+'.'+state.edition;}
function saveProgress(force=false){if(!state.document)return Promise.resolve();if(state.player){const saved=state.player.state();state.sceneStates[saved.scene_id]=saved;state.progress={...state.progress,...saved};}const body={...state.progress,learner_id:state.learner,section_id:state.activeSection?.id,scene_id:state.activeScene?.id,scene_states:{...state.sceneStates}},json=JSON.stringify(body);if(json===state.lastSaved&&!force)return state.saveChain;state.lastSaved=json;if(state.offline){safeStore.set(progressKey(),json);return Promise.resolve();}const path='/api/progress/'+encodeURIComponent(state.document.id)+'?'+docParams();state.saveChain=state.saveChain.then(()=>api(path,body,'PUT')).then(()=>notice('Place & experiment saved.')).catch(e=>{state.lastSaved='';notice(e.message,true);});return state.saveChain;}

function sourceElement(block){
 const article=make('article',{class:'source-block',id:'source-'+block.id,'data-block':block.id});
 if(block.kind==='equation'||block.kind==='math'||block.latex){const math=make('div',{class:'equation'});if(window.katex){try{window.katex.render(block.latex||block.text,math,{throwOnError:false,displayMode:true,trust:false,strict:'warn',maxExpand:1000,maxSize:20,macros:{}});}catch{math.append(make('pre',{},block.latex||block.text));}}else math.append(make('pre',{},block.latex||block.text));article.append(math);}
 else if(block.kind==='table'&&block.rows?.length){const table=make('table'),body=make('tbody');for(const cells of block.rows){const row=make('tr');for(const value of cells)row.append(make('td',{},typeof value==='string'?value:JSON.stringify(value)));body.append(row);}table.append(body);article.append(table);}
 else if(block.kind==='code')article.append(make('pre',{},block.text));
 else article.append(make('p',{},block.text));
 const tools=make('div',{class:'block-tools'}),link=sourceURL(block);tools.append(link?extLink(block.anchor?.page?'Original · page '+block.anchor.page:'View original ↗',link):make('span',{},'Source '+block.id));if(!state.offline){const note=make('button',{type:'button'},'+ Note on this passage');note.onclick=()=>{const select=$('#note-anchor'),textarea=$('#note-text');if(select&&textarea){select.value=block.id;textarea.scrollIntoView({block:'center',behavior:'instant'});textarea.focus();}};tools.append(note);}article.append(tools);return article;
}
function renderNotebook(container){
 clear(container);container.append(make('p',{class:'eyebrow'},'YOUR MARGINALIA'),make('h3',{},'Keep what clicks.'));
 const list=make('div');for(const note of state.notes){const article=make('article',{class:'note-card'});article.append(make('span',{class:'note-kind'},note.kind||'Note'),make('p',{},note.text||''),make('span',{class:'note-meta'},note.provenance?.basis==='agent-authored'?'Authored by your agent':'Your note'));const actions=make('div',{class:'actions'});for(const anchor of note.anchors||[]){const b=make('button',{type:'button',class:'text-button'},'Return to passage');b.onclick=()=>showSource(anchor.block_id);actions.append(b);}const del=make('button',{type:'button',class:'quiet'},'Remove');del.onclick=async()=>{try{await api('/api/annotations/'+encodeURIComponent(note.id),{learner_id:state.learner,expected_revision:note.revision},'DELETE');state.notes=state.notes.filter(x=>x.id!==note.id);renderNotebook(container);}catch(e){notice(e.message,true);}};actions.append(del);article.append(actions);list.append(article);}if(!state.notes.length)list.append(make('p',{class:'muted'},'Save a question, a connection, or a useful realization beside the passage that sparked it.'));container.append(list);
 const form=make('form',{class:'note-form'}),label=make('label',{for:'note-text'},'A note to come back to'),text=make('textarea',{id:'note-text',rows:4,required:'',placeholder:'This connects to…'}),kind=make('select',{'aria-label':'Note kind'});for(const[k,t]of [['note','Note'],['question','Question'],['insight','Insight']])kind.append(make('option',{value:k},t));const select=make('select',{id:'note-anchor','aria-label':'Source passage for the note'});select.append(make('option',{value:''},'The source as a whole'));for(const s of [state.activeSection].filter(Boolean))for(const b of s.blocks||[])select.append(make('option',{value:b.id},s.title+' · '+b.text.slice(0,70)));const button=make('button',{class:'primary'},'Save note'),error=make('p',{class:'inline-error',hidden:'',role:'alert'});form.append(label,text,kind,select,error,make('div',{class:'actions'}));form.lastChild.append(button);form.onsubmit=async e=>{e.preventDefault();button.disabled=true;try{const saved=await api('/api/documents/'+encodeURIComponent(state.document.id)+'/annotations',{learner_id:state.learner,text:text.value.trim(),kind:kind.value,anchors:select.value?[{block_id:select.value}]:[],tags:[],provenance:{basis:'user-stated'}});state.notes.push(saved);renderNotebook(container);notice('Note saved beside the source.');}catch(err){error.hidden=false;error.textContent=err.message;button.disabled=false;}};container.append(form);
}
async function createEdition(){simpleDialog('Another way into this source',dialog=>{const form=make('form'),label=make('label',{for:'edition-title'},'Name this explanation'),input=make('input',{id:'edition-title',required:'',placeholder:'Geometric intuition · first principles · deep dive…'}),cloneLabel=make('label',{class:'check-label'}),clone=make('input',{type:'checkbox'});clone.checked=true;cloneLabel.append(clone,document.createTextNode('Start from the current default explanation'));const help=make('p',{class:'muted'},'Your agent can reshape this edition around another question or level of detail. Its scenes and place are saved separately.'),error=make('p',{class:'inline-error',hidden:'',role:'alert'}),button=make('button',{class:'primary'},'Create edition');form.append(label,input,cloneLabel,help,error,make('div',{class:'actions'}));form.lastChild.append(button);form.onsubmit=async e=>{e.preventDefault();button.disabled=true;try{const edition=await api('/api/documents/'+encodeURIComponent(state.document.id)+'/editions',{learner_id:state.learner,title:input.value.trim(),clone_default:clone.checked});dialog.close();window.location.hash=routeLink(state.document.id,state.activeSection?.id,null,{edition:edition.id,mode:state.mode});}catch(err){error.hidden=false;error.textContent=err.message;button.disabled=false;}};dialog.append(form);});}
function readerHeader(){const d=state.document,header=make('header',{class:'reader-header'}),top=make('div',{class:'reader-topline'});top.append(make('a',{href:'#library'},'← YOUR LIBRARY'));const actions=make('div',{class:'actions'});if(!state.offline){const collection=make('button',{type:'button',class:'quiet'},'Add to collection');collection.onclick=()=>addToCollection().catch(e=>notice(e.message,true));const refresh=make('button',{type:'button',class:'quiet'},'Refresh explanation');refresh.onclick=()=>navigate(true);const exp=make('a',{href:'/api/documents/'+encodeURIComponent(d.id)+'/export?'+docParams(),download:'',class:'quiet'},'Export ↗');actions.append(collection,refresh,exp);if(d.source?.cache_path)actions.append(make('a',{href:'/api/documents/'+encodeURIComponent(d.id)+'/source',download:'',class:'quiet'},'Download retained original ↗'));}top.append(actions);header.append(top,make('h1',{},d.title));const meta=make('div',{class:'reader-meta'}),url=externalURL(d.source?.canonical_url||d.source?.content_url);meta.append(make('span',{},(d.source?.arxiv_id?'arXiv '+d.source.arxiv_id:'Imported '+(d.source?.format||'source'))+(d.source?.version?' · version '+d.source.version:'')),make('span',{},(d.sections?.length||0)+' sections'));if(url)meta.append(extLink('Original source ↗',url));if(d.source?.authors?.length)meta.append(make('span',{},d.source.authors.slice(0,3).join(', ')+(d.source.authors.length>3?' et al.':'')));header.append(meta);const bottom=make('div',{class:'reader-bottom'}),tabs=make('nav',{class:'view-tabs','aria-label':'Ways to explore this source'});for(const[mode,label]of [['experiment','Experiment'],['read','Read'],['connections','Connections']])tabs.append(make('a',{href:routeLink(d.id,state.activeSection?.id,state.activeScene?.id,{mode}),class:state.mode===mode?'active':'','aria-current':state.mode===mode?'page':'false'},label));bottom.append(tabs);if(!state.offline){const edition=make('div',{class:'edition-control'});edition.append(make('label',{for:'edition-select'},'Explanation'));const select=make('select',{id:'edition-select'});for(const item of state.editions)select.append(make('option',{value:item.id},item.title||'Original exploration'));select.value=state.edition||'default';select.onchange=()=>{window.location.hash=routeLink(d.id,state.activeSection?.id,null,{mode:state.mode,edition:select.value});};const add=make('button',{type:'button',class:'quiet'},'+ Edition');add.onclick=createEdition;edition.append(select,add);bottom.append(edition);}header.append(bottom);return header;}
function sectionNavigator(desktop){
 const sections=state.document.sections||[],container=make(desktop?'nav':'div',{class:desktop?'outline':'section-nav','aria-label':'Source sections'});
 if(desktop)container.append(make('p',{class:'outline-heading'},'INSIDE THIS SOURCE'));
 const input=make('input',{type:'search',class:'outline-search','aria-label':'Find a source section',placeholder:'Find a section…'}),list=make('div'),pagination=make('div',{class:'outline-pagination'});if(sections.length>45)container.append(input);container.append(list,pagination);
 let offset=Math.max(0,sections.findIndex(x=>x.id===state.activeSection?.id)-20),query='';
 const paint=()=>{clear(list);clear(pagination);const matched=query?sections.filter(x=>x.title.toLowerCase().includes(query)):sections;offset=Math.max(0,Math.min(offset,Math.max(0,matched.length-1)));const shown=matched.slice(offset,offset+60);
  if(desktop){for(const section of shown){const count=(state.storyboard?.scenes||[]).filter(c=>c.section_id===section.id).length,a=make('a',{href:routeLink(state.document.id,section.id,null,{mode:state.mode}),'aria-current':state.activeSection?.id===section.id?'true':'false'},section.title);a.style.paddingLeft=10+Math.min(3,Math.max(0,(section.level||1)-1))*10+'px';if(count)a.append(make('span',{class:'scene-count'},'◌ '+count));list.append(a);}}
  else{const select=make('select',{'aria-label':'Source section'});for(const section of shown)select.append(make('option',{value:section.id},section.title));if(shown.some(x=>x.id===state.activeSection?.id))select.value=state.activeSection.id;else select.selectedIndex=-1;select.onchange=()=>{window.location.hash=routeLink(state.document.id,select.value,null,{mode:state.mode});};list.append(select);}
  if(!shown.length)list.append(make('p',{class:'muted'},'No matching sections.'));
  if(matched.length>60){pagination.append(make('span',{},(offset+1)+'–'+Math.min(offset+60,matched.length)+' of '+matched.length));const prev=make('button',{type:'button','aria-label':'Show earlier sections'},'←'),next=make('button',{type:'button','aria-label':'Show later sections'},'→');prev.disabled=offset===0;next.disabled=offset+60>=matched.length;prev.onclick=()=>{offset=Math.max(0,offset-60);paint();};next.onclick=()=>{offset+=60;paint();};pagination.append(prev,next);}
 };input.oninput=()=>{query=input.value.trim().toLowerCase();offset=0;paint();};paint();return container;
}
function outline(){return sectionNavigator(true);}
function sectionSelect(){return sectionNavigator(false);}
function chooseScene(sectionId,sceneId){const scenes=state.storyboard?.stale?[]:state.storyboard?.scenes||[];return scenes.find(s=>s.id===sceneId)||scenes.find(s=>s.section_id===sectionId)||(!sectionId?scenes[0]:null);}
function experiment(container){
 const scene=state.activeScene,section=state.activeSection,grid=make('div',{class:'experiment-grid'}),main=make('div',{class:'experiment-main'}),tether=make('aside',{class:'source-tether','aria-label':'Source behind this explanation'});grid.append(main,tether);container.append(grid);
 if(scene){const all=state.storyboard.scenes||[],sequence=make('nav',{class:'scene-sequence','aria-label':'Explanation scenes'});for(const[s,c]of all.entries())sequence.append(make('a',{href:routeLink(state.document.id,c.section_id||section?.id,c.id,{mode:'experiment'}),class:c.id===scene.id?'active':''},String(s+1).padStart(2,'0')+' · '+c.title));main.append(sequence);const head=make('div',{class:'scene-heading'}),titles=make('div');titles.append(make('p',{class:'eyebrow'},'MAKE THE MECHANISM VISIBLE'),make('h2',{},scene.title));head.append(titles);main.append(head);const mount=make('section',{'aria-label':scene.title});main.append(mount);const saved=state.sceneStates[scene.id]||{};state.player=new ScenePlayer(mount,scene,saved,value=>{state.sceneStates[scene.id]=value;state.progress={...state.progress,...value};if(!state.painting)saveProgress();},showSource);main.append(make('p',{class:'scene-overview'},scene.explanation));
  tether.append(make('p',{class:'eyebrow'},'TETHERED TO THE SOURCE'),make('h3',{},section?.title||'Where the explanation comes from'));for(const anchor of scene.source_anchors||[]){const found=sourceBlock(anchor.block_id);if(!found)continue;const group=make('div'),quote=anchor.quote||found.block.text;group.append(make('div',{class:'source-quote'},quote.length>580?quote.slice(0,580)+'…':quote));const b=make('button',{type:'button',class:'anchor-link text-button'},(anchor.relation||'Source')+' · '+found.section.title+' ↗');b.onclick=()=>showSource(anchor.block_id);group.append(b);tether.append(group);}if(scene.assumptions?.length){const details=make('details',{class:'assumptions'});details.append(make('summary',{},'What this model simplifies'));for(const item of scene.assumptions)details.append(make('p',{},item));main.append(details);}
 }else{const empty=make('section',{class:'empty'});empty.append(make('p',{class:'eyebrow'},'A SOURCE, READY TO EXPLORE'),make('h2',{},state.storyboard?.stale?'The source has changed.':'Let your agent build the missing bridge.'),make('p',{},state.storyboard?.stale?'The saved explanation belongs to an earlier source revision. Ask your agent to review the changes and update the scenes.':'This section has no authored scene yet. Lucerna gives your agent the source, your learning context, and a visual instrument to build a tailored exploration.'));const read=make('a',{href:routeLink(state.document.id,section?.id,null,{mode:'read'}),class:'text-button'},'Read this section →');empty.append(read);main.append(empty);tether.append(make('p',{class:'eyebrow'},'THE QUESTION STARTS HERE'),make('h3',{},section?.title||state.document.title),make('p',{},section?.blocks?.[0]?.text?.slice(0,700)||'The source text remains available in Read mode.'));}
 main.append(questionBox(scene?'':'Help me understand '+(section?.title||state.document.title)+'. Build an explanation and an interactive model of the important mechanism.',scene?'explain':'visualize'));
}
function readSource(container,anchor){
 const grid=make('div',{class:'read-grid'}),left=make('div'),paper=make('section',{class:'source-document'}),s=state.activeSection;paper.append(make('p',{class:'eyebrow'},'THE SOURCE, IN ITS OWN WORDS'),make('h2',{},s?.title||state.document.title));for(const b of s?.blocks||[])paper.append(sourceElement(b));if(!s?.blocks?.length)paper.append(make('p',{},'No text was extracted for this section. Open the retained source to inspect it.'));left.append(paper);
 const sections=state.document.sections||[],index=sections.findIndex(x=>x.id===s?.id),nav=make('nav',{class:'read-section-controls','aria-label':'Previous and next source sections'});if(index>0)nav.append(make('a',{href:routeLink(state.document.id,sections[index-1].id,null,{mode:'read'})},'← '+sections[index-1].title));if(index<sections.length-1)nav.append(make('a',{href:routeLink(state.document.id,sections[index+1].id,null,{mode:'read'})},sections[index+1].title+' →'));left.append(nav);grid.append(left);
 if(!state.offline){const notes=make('aside',{class:'notebook'});renderNotebook(notes);grid.append(notes);}container.append(grid);if(state.document.warnings?.length){const warnings=make('details',{class:'assumptions'});warnings.append(make('summary',{},'Source extraction notes'));for(const w of state.document.warnings)warnings.append(make('p',{},w));container.append(warnings);}container.append(questionBox());if(anchor){const target=paper.querySelector('[data-block="'+CSS.escape(anchor)+'"]');if(target){target.classList.add('highlight');requestAnimationFrame(()=>target.scrollIntoView({block:'center',behavior:'instant'}));}}
}
async function reader(id,q,force=false){
 const turn=state.route,edition=q.get('edition')||'default';const needDoc=state.document?.id!==id||force;destroyPlayer();$('#main').replaceChildren(loading());const encoded=encodeURIComponent(id);state.edition=edition;
 const docRequest=state.offline?Promise.resolve(snapshot.document):needDoc?api('/api/documents/'+encoded):Promise.resolve(state.document);
 const requests=state.offline?[docRequest,Promise.resolve(snapshot.storyboard),Promise.resolve(snapshot.progress||{}),Promise.resolve({items:[]}),Promise.resolve({items:[]})]:[docRequest,api('/api/documents/'+encoded+'/storyboard?'+docParams()),api('/api/progress/'+encoded+'?'+docParams()),api('/api/documents/'+encoded+'/editions?'+params()),api('/api/documents/'+encoded+'/annotations?'+params())];
 const[document,storyboard,progress,editions,notes]=await Promise.all(requests);if(turn!==state.route)return;state.document=document;state.storyboard=storyboard;state.progress=progress||{};state.editions=editions.items||[];state.notes=notes.items||[];if(state.offline){try{state.progress=JSON.parse(safeStore.get(progressKey())||'null')||progress||{};}catch{}}
 const valid=new Set((storyboard?.scenes||[]).map(x=>x.id));state.sceneStates=Object.fromEntries(Object.entries(state.progress.scene_states||{}).filter(([key])=>valid.has(key)));if(state.progress.scene_id&&!state.sceneStates[state.progress.scene_id])state.sceneStates[state.progress.scene_id]={time:state.progress.time??state.progress.step,parameters:state.progress.parameters};state.mode=['experiment','read','connections'].includes(q.get('mode'))?q.get('mode'):'experiment';
 const explicit=q.get('section'),sceneId=q.get('scene')||(!explicit?state.progress.scene_id:null);state.activeScene=chooseScene(explicit||state.progress.section_id,sceneId);const sec=explicit||state.activeScene?.section_id||state.progress.section_id;state.activeSection=document.sections.find(x=>x.id===sec)||document.sections[0];if(!explicit&&!state.activeScene&&storyboard?.scenes?.length&&!storyboard.stale){state.activeScene=storyboard.scenes[0];state.activeSection=document.sections.find(x=>x.id===state.activeScene.section_id)||state.activeSection;}
 const main=$('#main');clear(main);main.append(readerHeader());const layout=make('div',{class:'reader-layout'}),workspace=make('div',{class:'reading-workspace'});layout.append(outline(),workspace);workspace.append(sectionSelect());main.append(layout);state.painting=true;
 if(state.mode==='read')readSource(workspace,q.get('anchor'));else if(state.mode==='connections')await graph(workspace);else experiment(workspace);
 state.painting=false;state.lastSaved='';saveProgress();
}

const svg=(tag,attrs={},text)=>{const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));if(text!==undefined)e.textContent=text;return e;};
function graphConnectionForm(container){
 const details=make('details',{class:'connection-form'});details.append(make('summary',{},'+ Connect two ideas'));const form=make('form');
 const fields={};for(const[id,label,placeholder]of [['from','From idea','The idea in this source'],['to','To idea','A prerequisite, a parallel, a useful contrast']]){const input=make('input',{id:'connection-'+id,required:'',placeholder});fields[id]=input;form.append(make('label',{for:'connection-'+id},label),input);}
 const toDocument=make('select',{'aria-label':'Source for the connected idea'});toDocument.append(make('option',{value:state.document.id},'This source'));api('/api/library?'+params()).then(response=>{for(const d of response.items||[])if(d.id!==state.document.id)toDocument.append(make('option',{value:d.id},d.title));}).catch(()=>{});form.append(make('label',{},'The other idea appears in'),toDocument);const relation=make('select',{'aria-label':'Connection relationship'});for(const r of ['explains','requires','contrasts','extends','related'])relation.append(make('option',{value:r},r));const explanation=make('textarea',{rows:3,required:'','aria-label':'Why these ideas connect',placeholder:'What is the actual connection?'}),error=make('p',{class:'inline-error',hidden:'',role:'alert'}),save=make('button',{class:'primary'},'Save connection');form.append(make('label',{},'Relationship'),relation,make('label',{},'Why the connection matters'),explanation,error,make('div',{class:'actions'}));form.lastChild.append(save);
 form.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{await api('/api/documents/'+encodeURIComponent(state.document.id)+'/connections',{learner_id:state.learner,from:{label:fields.from.value.trim(),document_id:state.document.id},to:{label:fields.to.value.trim(),document_id:toDocument.value},relation:relation.value,explanation:explanation.value.trim(),provenance:{basis:'user-stated'}});await navigate(true);notice('Connection saved.');}catch(err){error.hidden=false;error.textContent=err.message;save.disabled=false;}};details.append(form);container.append(details);
}
async function graph(container){
 if(state.offline){container.append(make('section',{class:'empty'}));container.lastChild.append(make('h2',{},'Connections live in your workspace.'),make('p',{},'This export carries the source and its interactive scenes. Return to Lucerna to follow your saved connections and learning paths.'));return;}
 const turn=state.route,response=await api('/api/graph?'+params({document_id:state.document.id}));if(turn!==state.route)return;state.connections=response;
 const toolbar=make('div',{class:'graph-toolbar'}),title=make('div');title.append(make('p',{class:'eyebrow'},'FOLLOW A CONNECTION'),make('h2',{},'Ideas get stronger in company.'));const filter=make('select',{'aria-label':'Connection relationship filter'});filter.append(make('option',{value:''},'Every relationship'));for(const r of ['requires','explains','contrasts','extends','related'])filter.append(make('option',{value:r},r));toolbar.append(title,filter);container.append(toolbar);
 const layout=make('div',{class:'graph-layout'}),left=make('div'),stage=make('div',{class:'graph-stage'}),inspector=make('aside',{class:'graph-inspector'});left.append(stage);layout.append(left,inspector);container.append(layout);
 const nodes=response.nodes||[],edges=response.edges||[];let chosen=nodes.find(n=>n.document_id===state.document.id)||nodes[0],graphView,positions=new Map(),zoom=1;
 const inspect=node=>{chosen=node;clear(inspector);inspector.append(make('p',{class:'eyebrow'},node.kind==='paper'?'CONNECTED SOURCE':'CONCEPT'),make('h3',{},node.label));const connected=edges.filter(e=>e.from===node.id||e.to===node.id);if(!connected.length)inspector.append(make('p',{},'No relationship has been authored for this idea yet.'));for(const edge of connected){const other=nodes.find(n=>n.id===(edge.from===node.id?edge.to:edge.from)),article=make('article',{class:'note-card'});article.append(make('span',{class:'relation-label'},(edge.from===node.id?'→ ':'← ')+edge.relation),make('h4',{},other?.label||'Connected idea'),make('p',{},edge.explanation||''),make('small',{},edge.provenance?.basis==='agent-authored'?'Connection authored by your agent':'Connection you saved'));if(other?.document_id){const a=make('a',{href:routeLink(other.document_id,null,null,{mode:'connections',edition:'default'}),class:'text-button'},'Open linked source →');article.append(a);}for(const anchor of edge.anchors||[]){if(anchor.block_id){const b=make('button',{type:'button',class:'text-button'},'Inspect supporting passage');b.onclick=()=>{if(anchor.document_id&&anchor.document_id!==state.document.id)window.location.hash=routeLink(anchor.document_id,anchor.section_id,null,{mode:'read',anchor:anchor.block_id,edition:'default'});else showSource(anchor.block_id);};article.append(b);}}const remove=make('button',{type:'button',class:'quiet'},'Remove connection');remove.onclick=async()=>{try{await api('/api/connections/'+encodeURIComponent(edge.id),{learner_id:state.learner},'DELETE');navigate(true);}catch(e){notice(e.message,true);}};article.append(remove);inspector.append(article);}if(node.document_id&&node.document_id!==state.document.id)inspector.append(make('a',{href:routeLink(node.document_id,null,null,{edition:'default'}),class:'text-button'},'Explore this source →'));graphConnectionForm(inspector);};
 const draw=()=>{
  clear(stage);positions=new Map();const filtered=edges.filter(e=>!filter.value||e.relation===filter.value),included=new Set(filtered.flatMap(e=>[e.from,e.to])),visible=(filter.value?nodes.filter(n=>included.has(n.id)):nodes).slice(0,70);graphView=svg('svg',{viewBox:'0 0 1000 620',role:'group','aria-label':'Saved concept connections. Select a node to inspect the relationship and source.'});graphView.append(svg('title',{},'Source and concept connections'));const defs=svg('defs'),marker=svg('marker',{id:'graph-arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:6,markerHeight:6,orient:'auto-start-reverse'});marker.append(svg('path',{d:'M 0 0 L 10 5 L 0 10',fill:'none',stroke:'#688694','stroke-width':1.5}));defs.append(marker);graphView.append(defs);
  const center=visible.find(n=>n.document_id===state.document.id)||visible[0],others=visible.filter(n=>n.id!==center?.id);if(center)positions.set(center.id,{x:500,y:310});others.forEach((n,i)=>{const ring=others.length>16&&i>=16?2:1,within=ring===1?i:i-16,total=ring===1?Math.min(16,others.length):others.length-16,a=-Math.PI/2+within*Math.PI*2/Math.max(1,total),rx=ring===1?275:440,ry=ring===1?200:275;positions.set(n.id,{x:500+Math.cos(a)*rx,y:310+Math.sin(a)*ry});});
  for(const edge of filtered){const from=positions.get(edge.from),to=positions.get(edge.to);if(!from||!to)continue;const dx=to.x-from.x,dy=to.y-from.y,distance=Math.hypot(dx,dy)||1,startRadius=edge.from===center?.id?36:22,endRadius=edge.to===center?.id?36:22;const line=svg('line',{x1:from.x+dx*startRadius/distance,y1:from.y+dy*startRadius/distance,x2:to.x-dx*endRadius/distance,y2:to.y-dy*endRadius/distance,stroke:edge.relation==='contrasts'?'#a88b78':'#66838f','stroke-width':1.5,'stroke-dasharray':edge.relation==='related'?'5 5':'none','marker-end':'url(#graph-arrow)'});line.append(svg('title',{},edge.relation+': '+(edge.explanation||'')));graphView.append(line);}
  for(const node of visible){const p=positions.get(node.id),central=node.id===center?.id,g=svg('g',{class:'graph-node',tabindex:0,role:'button','aria-label':node.label+', '+node.kind,transform:'translate('+p.x+' '+p.y+')'});g.append(svg('circle',{r:central?33:node.kind==='paper'?18:12,fill:central?'#2e3940':node.kind==='paper'?'#193b4a':'#224339',stroke:central?'#e9c796':node.kind==='paper'?'#8fd8ed':'#a1d9bd','stroke-width':central?2:1.5}));g.append(svg('text',{x:0,y:central?6:4,'text-anchor':'middle',fill:central?'#e9c796':'#bcced4','font-size':central?22:10,'aria-hidden':'true'},central?'◌':node.kind==='paper'?'▤':'·'));const label=node.label.length>39?node.label.slice(0,36)+'…':node.label;g.append(svg('text',{x:0,y:central?60:35,'text-anchor':'middle',fill:central?'#e9dfca':'#bac9d0','font-size':central?16:12},label),svg('title',{},node.label));g.onclick=()=>inspect(node);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();inspect(node);}};graphView.append(g);}stage.append(graphView);if(!visible.length)stage.append(make('p',{class:'notice'},'No connections match this relationship yet.'));
 };
 if(!edges.length){stage.append(make('section',{class:'empty'}));stage.lastChild.append(make('h2',{},'Give the idea a neighbor.'),make('p',{},'Connections are saved explanations of how ideas relate. Add one below or ask your agent to map prerequisites, parallels, and contrasts from the actual sources.'));}else draw();
 const tools=make('div',{class:'actions'});for(const[label,factor]of [['−',.8],['+',1.25]]){const b=make('button',{type:'button','aria-label':factor>1?'Zoom into graph':'Zoom out of graph'},label);b.onclick=()=>{zoom=Math.max(.5,Math.min(2.5,zoom*factor));if(graphView)graphView.setAttribute('viewBox',(500-500/zoom)+' '+(310-310/zoom)+' '+1000/zoom+' '+620/zoom);};tools.append(b);}const reset=make('button',{type:'button'},'Fit connections');reset.onclick=()=>{zoom=1;if(graphView)graphView.setAttribute('viewBox','0 0 1000 620');};tools.append(reset);if(edges.length)left.append(tools);
 if(nodes.length>70)left.append(make('p',{class:'muted'},'The diagram shows 70 ideas at a time. The list below includes all saved connections.'));const accessible=make('details',{class:'context-note'});accessible.append(make('summary',{},'Browse the connected ideas ('+nodes.length+')'));const list=make('div',{class:'graph-node-list'});for(const node of nodes){const b=make('button',{type:'button'},node.label);b.onclick=()=>inspect(node);list.append(b);}accessible.append(list);left.append(accessible);if(chosen)inspect(chosen);else{inspector.append(make('p',{class:'muted'},'Saved relationships will appear here with their explanation and provenance.'));graphConnectionForm(inspector);}filter.onchange=draw;container.append(questionBox('Map the useful conceptual connections around this source. Ground each relationship in the source and connect relevant papers already in my library.','explain',{intent:'map_connections'}));
}
function memoryContext(context){
 const d=make('details',{class:'context-note'}),conflicts=context?.unresolved_conflicts||[],summary=make('summary',{},'What your tutor carries forward');if(conflicts.length)summary.append(make('span',{class:'memory-conflict'},' · '+conflicts.length+' to reconcile'));d.append(summary);
 const memories=(context?.memories||[]).filter(m=>m.status!=='forgotten'&&m.status!=='retired').slice(0,12),conflicted=new Set(conflicts.flatMap(c=>c.memory_ids||[]));
 if(context?.learner?.context)d.append(make('p',{},context.learner.context));
 if(conflicts.length)d.append(make('p',{class:'memory-reconciliation'},'Some remembered observations disagree. Your tutor should reconcile them in context, rather than silently choosing one.'));
 const show=(m,conditional=false)=>{const item=make('div',{class:'memory-observation'});item.append(make('p',{},m.content||m.text||m.summary||''));const labels=[];
  if(conflicted.has(m.id))labels.push('Needs reconciliation');
  if(conditional)labels.push('Applies only in the stated context');
  if(m.evidence?.basis==='inferred')labels.push('Working inference');else if(m.evidence?.basis==='observed')labels.push('Observed in conversation');else if(m.evidence?.basis==='user-stated')labels.push('User-stated');
  if(Object.keys(m.applies_when||{}).length)labels.push(Object.entries(m.applies_when).map(([k,v])=>k+': '+v).join(' · '));
  for(const[field,label]of [['valid_from','From'],['valid_to','Until'],['expires_at','Review after']])if(m[field]){const date=new Date(m[field]);labels.push(label+' '+(Number.isNaN(date.getTime())?m[field]:date.toLocaleString()));}
  if(labels.length)item.append(make('small',{},labels.join(' · ')));
  const qualifications=(context?.memory_relations||[]).filter(r=>r.relation==='qualifies'&&r.target_id===m.id&&r.source);for(const relation of qualifications){const q=make('p',{class:'memory-qualification'},'Qualification: '+(relation.source.text||''));item.append(q);}
  return item;};
 for(const m of memories)d.append(show(m));
 const candidates=context?.contextual_candidates||[];if(candidates.length){const conditional=make('details',{class:'conditional-memory'});conditional.append(make('summary',{},'Context-dependent observations ('+candidates.length+')'));for(const item of candidates)conditional.append(show(item.memory||item,true));d.append(conditional);}
 if(!memories.length&&!context?.learner?.context)d.append(make('p',{},'Useful connections, open questions, your current aims, and what helped you understand can carry forward from your teaching conversation.'));
 d.append(make('small',{},'Revisable observations, not grades or permanent labels.'));return d;
}
async function pathways(){
 destroyPlayer();state.document=null;state.activeScene=null;state.activeSection=null;state.edition='';const turn=state.route,main=$('#main'),page=make('div',{class:'page'});clear(main);page.append(make('p',{class:'eyebrow'},'LEARNING PATHS'),make('h1',{},'A direction,\nwith room to wander.'),make('p',{class:'intro muted'},'Keep the larger journey in view while your agent adapts the next move to the conversation. Every topic stays open.'));main.append(page);if(state.offline){page.append(make('p',{class:'notice'},'Learning paths live in your local workspace. This export carries the source and its scenes.'));return;}
 const[response,context]=await Promise.all([api('/api/learning/pathways?'+params()),api('/api/learning/context?'+params())]);if(turn!==state.route)return;const items=response.items||[];if(!items.length){page.append(make('section',{class:'empty'},'No learning path is saved yet.'),questionBox('Help me plan a learning path for the topic I want to learn. Use our conversation to choose a useful starting point and sequence.','explain',{intent:'create_learning_path'}),memoryContext(context));return;}
 let target=items[0];const select=make('select',{class:'learning-select','aria-label':'Choose a learning path'});for(const[i,item]of items.entries())select.append(make('option',{value:i},item.pathway?.title||item.curriculum?.title||item.plan?.title||'Learning path'));if(items.length>1)page.append(select);const detail=make('div');page.append(detail);
 const paint=()=>{clear(detail);const curriculum=target.curriculum||{},plan=target.plan?.plan||target.plan||{},layout=make('div',{class:'path-layout'}),intro=make('aside');intro.append(make('p',{class:'eyebrow'},curriculum.title||'CURRENT DIRECTION'),make('p',{class:'path-goal'},plan.goal||curriculum.goal||'Follow the next useful connection.'));if(typeof plan.guidance==='string')intro.append(make('p',{class:'muted'},plan.guidance));intro.append(memoryContext(context));const flow=make('div',{class:'path-flow'}),nodes=plan.nodes||curriculum.nodes||[];
  const open=n=>{const resource=(n.resources||[]).find(r=>typeof r==='string'||r.id||r.url);if(resource?.id){window.location.hash=routeLink(resource.id,null,null,{edition:'default'});return;}const url=typeof resource==='string'?externalURL(resource):externalURL(resource?.url);if(url){window.open(url,'_blank','noopener,noreferrer');return;}const q=detail.querySelector('textarea');if(q){q.value="Let's explore "+n.title+'. '+(n.description||'')+' Use my current pathway ('+curriculum.id+') and what you remember from our conversation.';q.scrollIntoView({block:'center'});q.focus();}};
  for(const[i,n]of nodes.entries()){const next=n.id===plan.next_node_id,row=make('article',{class:'path-node'+(next?' next':'')});row.append(make('span',{class:'path-number'},String(i+1).padStart(2,'0')));const body=make('div');if(next)body.append(make('p',{class:'eyebrow'},'A USEFUL NEXT STEP'));body.append(make('h3',{},n.title),make('p',{},n.description||''),make('small',{},n.reason||n.status||'Open to explore'));if(n.prerequisites?.length)body.append(make('small',{},'Builds on: '+n.prerequisites.map(id=>(curriculum.nodes||[]).find(x=>x.id===id)?.title||id).join(', ')));row.append(body);const button=make('button',{type:'button'},n.resources?.length?'Open':'Explore with agent');button.onclick=()=>open(n);row.append(button);flow.append(row);}
  if(plan.deferred?.length){const later=make('details',{class:'context-note'});later.append(make('summary',{},'Later on this path ('+plan.deferred.length+')'));for(const n of plan.deferred){const row=make('div',{class:'deferred-node'});row.append(make('h3',{},n.title),make('p',{},n.deferred_reason||n.reason||'Available whenever you want to explore it.'));const b=make('button',{type:'button'},'Explore this topic');b.onclick=()=>open(n);row.append(b);later.append(row);}flow.append(later);}if(!nodes.length)flow.append(make('p',{class:'notice'},'No next topics are selected yet. Ask your agent to adjust the focus or target.'));layout.append(intro,flow);detail.append(layout,questionBox('','explain',{curriculum_id:curriculum.id,pathway_id:target.pathway?.id,intent:'continue_learning_path'}));};select.onchange=()=>{target=items[Number(select.value)];paint();};paint();
}
let inboxTimer;
async function refreshQuestions(){
 const target=$('#question-inbox'),learner=state.learner;try{const response=await api('/api/requests?'+params());if(learner!==state.learner)return;clear(target);const intro=make('p',{class:'muted'},'Saved questions wait for your teaching agent. Replies appear here after the agent completes them in your workspace.');target.append(intro);const refresh=make('button',{type:'button',class:'quiet'},'Refresh replies');refresh.onclick=refreshQuestions;target.append(refresh);
 if(!response.items?.length){target.append(make('div',{class:'empty'},'No saved questions yet. Open a source and follow the question that catches you.'));return;}
 for(const request of [...response.items].reverse()){const item=make('article',{class:'question-inbox-item'}),expired=request.status==='in_progress'&&request.claim?.expires_at&&Number(request.claim.expires_at)*1000<Date.now(),status=expired?'Ready to resume':{pending:'Saved for your agent',in_progress:'In progress',complete:'Reply ready',failed:'Needs attention',cancelled:'Cancelled'}[request.status]||request.status;item.append(make('span',{class:'request-status'},status),make('h3',{},request.question||request.body?.question||'Saved question'));if(request.result){const result=request.result,answer=typeof result==='string'?result:result.answer||result.text||result.reply||result.summary||result.explanation||result.message;const box=make('div',{class:'request-result'});box.append(make('p',{},typeof answer==='string'?answer:'Your agent completed this request. Reopen the exploration to see the changes.'));item.append(box);}
 const actions=make('div',{class:'actions'}),feedback=make('div',{class:'question-feedback',role:'status'});if(request.result?.document_id||request.document_id){const documentId=request.result?.document_id||request.document_id,editionId=request.result?.edition_id||request.edition_id||'default',sameDocument=documentId===request.document_id,sameEdition=editionId===(request.edition_id||'default');const a=make('a',{href:routeLink(documentId,sameDocument?request.section_id:null,request.result?.scene_id||(sameDocument&&sameEdition?request.scene_id:null),{edition:editionId})},request.status==='complete'?'Open the updated exploration →':'Return to the source →');a.onclick=()=>$('#questions-dialog').close();actions.append(a);}if(request.status==='pending'||request.status==='failed'||expired){const b=make('button',{type:'button'},'Copy request to my agent');b.onclick=()=>copy('Use Lucerna in the saved workspace for learner '+state.learner+'. Pick up saved request '+request.id+' and read its authoring packet. '+(request.question||'')+' Complete the request with your response and any revised exploration.',feedback);actions.append(b);}item.append(actions,feedback);target.append(item);}
 }catch(e){target.replaceChildren(make('p',{class:'inline-error'},e.message));}}
function openQuestions(){if(state.offline)return;$('#questions-dialog').showModal();refreshQuestions();clearInterval(inboxTimer);inboxTimer=setInterval(()=>{if($('#questions-dialog').open&&!document.hidden)refreshQuestions();},10000);}
let commandTimer,commandSerial=0;
async function commandSearch(){const serial=++commandSerial,q=$('#command-query').value.trim(),target=$('#command-results');if(!q){target.replaceChildren(make('p',{class:'muted'},'Search finds passages inside your papers and books, with a path back to the exact source.'));return;}target.replaceChildren(loading('Searching source text…'));try{const result=await api('/api/search?'+params({q,limit:20}));if(serial!==commandSerial)return;clear(target);for(const hit of result.items||[]){const a=make('a',{href:routeLink(hit.document_id,hit.section_id,null,{mode:'read',anchor:hit.block_id||'',edition:'default'}),class:'command-result'});a.append(make('small',{},hit.section_title||'Source match'),make('strong',{},hit.title),make('span',{},hit.snippet||''));a.onclick=()=>$('#search-dialog').close();target.append(a);}if(!result.items?.length)target.append(make('p',{class:'muted'},'No matching passages. Try a shorter phrase or a related concept.'));}catch(e){target.replaceChildren(make('p',{class:'inline-error'},e.message));}}
function openSearch(){if(state.offline)return;$('#search-dialog').showModal();$('#command-query').focus();commandSearch();}
function openImport(){if(state.offline)return;$('#import-dialog').showModal();$('#import-source').focus();}
async function navigate(force=false){
 const turn=++state.route;await saveProgress(true);destroyPlayer();const hash=window.location.hash.slice(1)||'library';try{if(hash==='pathways'){await pathways();}else if(hash.startsWith('document=')){const q=new URLSearchParams(hash),learner=q.get('learner');if(learner&&learner!==state.learner){state.learner=learner;state.collection='';$('#question-inbox').replaceChildren();$('#learner-select').value=learner;safeStore.set('lucerna.learner',learner);}await reader(q.get('document'),q,force);}else if(state.offline){await reader(snapshot.document.id,new URLSearchParams({edition:'default'}));}else await library();
 if(turn!==state.route)return;$('#library-nav').setAttribute('aria-current',!hash.startsWith('pathways')?'page':'false');$('#pathways-nav').setAttribute('aria-current',hash==='pathways'?'page':'false');if(!new URLSearchParams(hash).has('anchor'))window.scrollTo({top:0,behavior:'instant'});
 }catch(e){if(turn!==state.route)return;destroyPlayer();const page=make('div',{class:'page'});page.append(make('p',{class:'eyebrow'},'THE WORKSPACE NEEDS A MOMENT'),make('h1',{},'Let’s pick up the thread.'),make('p',{class:'inline-error',role:'alert'},e.message));const b=make('button',{type:'button',class:'primary'},'Retry');b.onclick=()=>navigate(true);page.append(b);$('#main').replaceChildren(page);}
}
$('#import-open').onclick=openImport;$('#import-close').onclick=()=>$('#import-dialog').close();$('#requests-open').onclick=openQuestions;$('#questions-close').onclick=()=>$('#questions-dialog').close();$('#questions-dialog').addEventListener('close',()=>clearInterval(inboxTimer));$('#search-open').onclick=openSearch;$('#search-close').onclick=()=>$('#search-dialog').close();$('#command-query').oninput=()=>{clearTimeout(commandTimer);commandTimer=setTimeout(commandSearch,230);};
$('#import-form').onsubmit=async e=>{e.preventDefault();const source=$('#import-source').value.trim(),text=$('#import-text').value.trim(),file=$('#import-file').files[0],button=$('#import-submit'),error=$('#import-error');if(!source&&!text&&!file){error.hidden=false;error.textContent='Add an arXiv link or ID, select a file, or paste source text.';return;}button.disabled=true;button.textContent='Reading source…';error.hidden=true;try{let body={source};if(file){if(file.size>25*1024*1024)throw new Error('For files larger than 25 MB, ask your agent to import the local file directly.');body.filename=file.name;body.source=file.name;if(file.name.toLowerCase().endsWith('.pdf')){const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));body.content=btoa(binary);body.content_encoding='base64';}else body.content=await file.text();}else if(text){body.content=text;body.filename='Pasted source.txt';body.source=source||'Pasted source';}const doc=await api('/api/import',body);$('#import-dialog').close();$('#import-form').reset();window.location.hash=routeLink(doc.id,null,null,{edition:'default'});}catch(err){error.hidden=false;error.textContent=err.message;}finally{button.disabled=false;button.textContent='Import source';}};
window.addEventListener('hashchange',()=>navigate());window.addEventListener('beforeunload',()=>{if(state.document){const body={...state.progress,learner_id:state.learner,section_id:state.activeSection?.id,scene_id:state.activeScene?.id,scene_states:{...state.sceneStates}};if(state.player)body.scene_states[state.player.scene.id]=state.player.state();if(state.offline)safeStore.set(progressKey(),JSON.stringify(body));else fetch('/api/progress/'+encodeURIComponent(state.document.id)+'?'+docParams(),{method:'PUT',headers:{'Content-Type':'application/json','X-Teaching-Token':state.token},body:JSON.stringify(body),keepalive:true}).catch(()=>{});}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch();}});
async function start(){
 try{if(state.offline){for(const id of ['import-open','requests-open','search-open','learner-select'])$('#'+id).hidden=true;$('#connection').hidden=false;$('#connection').textContent='Exported exploration · Source, interactive scenes, and device narration work here. Your library, notes, and learning paths stay in Lucerna.';}else{const bootstrap=await api('/api/bootstrap');state.token=bootstrap.token;state.learner=safeStore.get('lucerna.learner')||bootstrap.learner_id||'default';const learners=await api('/api/learners');if(!(learners.items||[]).some(l=>l.id===state.learner))state.learner=bootstrap.learner_id||'default';for(const learner of learners.items||[])$('#learner-select').append(make('option',{value:learner.id},learner.name||learner.id));$('#learner-select').value=state.learner;$('#learner-select').onchange=async()=>{await saveProgress(true);destroyPlayer();const selected=$('#learner-select').value,id=state.document?.id;state.learner=selected;state.collection='';$('#question-inbox').replaceChildren();state.edition='default';state.lastSaved='';state.progress={};state.sceneStates={};state.document=null;safeStore.set('lucerna.learner',selected);if(id)window.location.hash=routeLink(id,null,null,{edition:'default'});else navigate(true);};}await navigate();}catch(e){$('#main').replaceChildren(make('div',{class:'page'}));$('#main').firstChild.append(make('h1',{},'Lucerna is waiting for its workspace.'),make('p',{class:'inline-error'},e.message));}
}
start();
