const NS='http://www.w3.org/2000/svg';
const number=n=>{if(!Number.isFinite(Number(n)))throw new Error('A scene calculation produced a non-finite value.');return Number(n);};
export function evaluate(expr,vars={},depth=0){
 if(depth>32)throw new Error('A calculation exceeds its nesting limit.');
 if(typeof expr==='number')return number(expr);
 if(!expr||typeof expr!=='object')throw new Error('A calculation must use the expression format.');
 if(Object.hasOwn(expr,'var')){if(!Object.hasOwn(vars,expr.var))throw new Error('Unknown variable: '+expr.var);return number(vars[expr.var]);}
 const a=(expr.args||[]).map(v=>evaluate(v,vars,depth+1));
 const ops={add:()=>a.reduce((s,v)=>s+v,0),sub:()=>a.length===1?-a[0]:a.slice(1).reduce((s,v)=>s-v,a[0]),mul:()=>a.reduce((s,v)=>s*v,1),div:()=>a[0]/a[1],pow:()=>a[0]**a[1],sin:()=>Math.sin(a[0]),cos:()=>Math.cos(a[0]),exp:()=>Math.exp(a[0]),log:()=>Math.log(a[0]),sqrt:()=>Math.sqrt(a[0]),abs:()=>Math.abs(a[0]),min:()=>Math.min(...a),max:()=>Math.max(...a),clamp:()=>Math.min(a[2],Math.max(a[1],a[0]))};
 if(!Object.hasOwn(ops,expr.op))throw new Error('Unsupported calculation: '+expr.op);return number(ops[expr.op]());
}
function html(tag,attrs={},text){const e=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==='class')e.className=v;else e.setAttribute(k,v);}if(text!==undefined)e.textContent=text;return e;}
function svg(tag,attrs={},text){const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));if(text!==undefined)e.textContent=text;return e;}
function tpl(text,vars){return String(text??'').replace(/\{\{([\w.-]+)(?::(\d+))?\}\}/g,(_,key,p)=>Object.hasOwn(vars,key)?(p===undefined?Number(vars[key].toPrecision(5)):vars[key].toFixed(Math.min(Number(p),8))):'['+key+']');}
const val=(v,vars,f=0)=>v===undefined?f:typeof v==='object'?evaluate(v,vars):number(v);
const clamp=v=>Math.max(0,Math.min(1,Number(v)||0));
const fmt=v=>Number(number(v).toPrecision(4)).toString();
export class ScenePlayer{
 constructor(container,scene,saved={},onChange=()=>{},onSource=()=>{}){
  this.root=container;this.scene=scene;this.onChange=onChange;this.onSource=onSource;this.time=clamp(saved.time??saved.step??0);this.controls={};this.inputs=new Map();this.playing=false;this.frame=0;this.lastNotify=0;this.destroyed=false;this.currentStep=-2;this.steps=[...(scene.steps||[])].sort((a,b)=>a.time-b.time);this.reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  for(const c of scene.controls||[])this.controls[c.id]=this.coerce(c,saved.parameters?.[c.id]??c.default);this.build();this.render();
 }
 coerce(c,v){if(c.type==='toggle')return v?1:0;if(c.type==='select'){const options=(c.options||[]).map(o=>typeof o==='object'?o.value:o);return options.some(o=>String(o)===String(v))?Number(v):Number(options[0]??c.default??0);}const n=Number(v??c.default??0),bounded=Math.min(c.max??100,Math.max(c.min??0,Number.isFinite(n)?n:Number(c.default??c.min??0)));return c.step?Math.min(c.max??100,Math.max(c.min??0,Number(((c.min??0)+Math.round((bounded-(c.min??0))/c.step)*c.step).toPrecision(12)))):bounded;}
 build(){
  this.root.replaceChildren();this.root.classList.add('scene-player');
  const stage=html('div',{class:'instrument-stage',tabindex:'0','aria-label':'Interactive scene. Space plays or pauses. Arrow keys step. Home resets.'});this.stage=stage;
  const stageLabel=html('div',{class:'stage-label'});stageLabel.append(html('span',{},'EXPERIMENT'),html('span',{class:'stage-duration'},(this.scene.duration||12)+' s · reversible'));stage.append(stageLabel);
  this.svg=svg('svg',{viewBox:'0 0 '+(this.scene.visual?.width||800)+' '+(this.scene.visual?.height||450),role:'img','aria-label':this.scene.alt_text||this.scene.title});
  this.svg.append(svg('title',{},this.scene.title),svg('desc',{},this.scene.alt_text||this.scene.explanation||''));this.drawing=svg('g');this.svg.append(this.drawing);stage.append(this.svg);this.root.append(stage);
  const rail=html('div',{class:'playback'});this.playButton=html('button',{type:'button',class:'play-button','aria-label':'Play animation'},this.reduced?'Advance':'Play');this.playButton.onclick=()=>this.playing?this.pause():this.play();
  const back=html('button',{type:'button',class:'icon-button','aria-label':'Previous animation step'},'←');back.onclick=()=>this.step(-1);
  const next=html('button',{type:'button',class:'icon-button','aria-label':'Next animation step'},'→');next.onclick=()=>this.step(1);
  const timeline=html('div',{class:'timeline'});this.range=html('input',{type:'range',min:0,max:1000,step:1,value:Math.round(this.time*1000),'aria-label':'Animation position'});this.range.oninput=()=>{this.pause();this.setTime(Number(this.range.value)/1000);};timeline.append(this.range);
  const marks=html('div',{class:'timeline-marks','aria-hidden':'true'});for(const step of this.steps){const mark=html('span',{title:step.title||''});mark.style.left=step.time*100+'%';marks.append(mark);}timeline.append(marks);
  this.position=html('output',{class:'time-display'},'0:00');rail.append(this.playButton,back,next,timeline,this.position);
  const expand=html('button',{type:'button',class:'icon-button','aria-label':'Expand scene'},'⛶');expand.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await this.root.requestFullscreen();}catch{this.error.hidden=false;this.error.textContent='The browser did not allow full screen. The scene remains available here.';}};rail.append(expand);this.root.append(rail);
  this.caption=html('div',{class:'scene-caption'});this.root.append(this.caption);
  if(this.reduced)this.root.append(html('p',{class:'motion-note'},'Reduced motion: use the steps or timeline to inspect each state.'));
  if(this.scene.presets?.length){const strip=html('div',{class:'preset-strip'});strip.append(html('span',{class:'control-heading'},'Compare a case'));for(const p of this.scene.presets){const b=html('button',{type:'button',class:'preset-button',title:p.description||p.title},p.title);b.onclick=()=>{this.pause();for(const c of this.scene.controls||[])this.setControl(c.id,c.default,false);for(const[id,v]of Object.entries(p.parameters||{}))this.setControl(id,v,false);this.render();this.notify(true);};strip.append(b);}this.root.append(strip);}
  if(this.scene.controls?.length){const panel=html('section',{class:'control-panel','aria-label':'Experiment controls'});const top=html('div',{class:'control-panel-heading'});top.append(html('h3',{},'Change something. See why it matters.'));const reset=html('button',{type:'button',class:'text-button'},'Reset');reset.onclick=()=>{this.pause();for(const c of this.scene.controls)this.setControl(c.id,c.default,false);this.time=0;this.render();this.notify(true);};top.append(reset);panel.append(top);const controls=html('div',{class:'parameters'});
   for(const c of this.scene.controls){const label=html('label',{class:'parameter'}),head=html('span',{class:'parameter-label'},c.label),out=html('output',{},fmt(this.controls[c.id]));let input;if(c.type==='select'){input=html('select');for(const raw of c.options||[]){const o=typeof raw==='object'?raw:{value:raw,label:String(raw)};input.append(html('option',{value:o.value},o.label));}input.value=String(this.controls[c.id]);}else if(c.type==='toggle'){input=html('input',{type:'checkbox'});input.checked=!!this.controls[c.id];label.classList.add('toggle-parameter');}else input=html('input',{type:'range',min:c.min??0,max:c.max??100,step:c.step??1,value:this.controls[c.id]});input.setAttribute('aria-label',c.label);input.oninput=()=>{this.pause();this.setControl(c.id,c.type==='toggle'?input.checked:input.value);};this.inputs.set(c.id,{input,out});head.append(out);label.append(head,input);if(c.description)label.append(html('small',{},c.description));controls.append(label);}panel.append(controls);this.root.append(panel);
  }
  const interactive=(this.scene.visual?.objects||[]).filter(o=>o.reveal||o.control_bind);if(interactive.length){const inspect=html('div',{class:'object-inspector'});inspect.append(html('span',{class:'control-heading'},'Inspect the mechanism'));for(const o of interactive){const b=html('button',{type:'button'},o.reveal?.title||o.label||o.id);b.onclick=()=>this.activate(o);inspect.append(b);}this.root.append(inspect);}
  this.reveal=html('div',{class:'object-reveal',hidden:''});this.root.append(this.reveal);
  const details=html('div',{class:'scene-details'});const values=html('details',{class:'current-values'});values.append(html('summary',{},'Current values'));this.readouts=html('div');values.append(this.readouts);details.append(values);
  const narrative=html('details',{class:'narrative-tools'});narrative.append(html('summary',{},'Narration & transcript'));const voiceLabel=html('label',{class:'check-label'});this.voiceToggle=html('input',{type:'checkbox'});voiceLabel.append(this.voiceToggle,document.createTextNode('Narrate playback with a device voice'));this.voiceToggle.onchange=()=>this.pause();narrative.append(voiceLabel);
  this.voiceStatus=html('small',{},'Checking installed voices…');this.voiceSelect=html('select',{'aria-label':'Narration voice'});this.rateSelect=html('select',{'aria-label':'Narration speed'});for(const rate of [.75,1,1.25,1.5])this.rateSelect.append(html('option',{value:rate},rate+'×'));this.rateSelect.value='1';const voiceControls=html('div',{class:'voice-controls'});voiceControls.append(this.voiceSelect,this.rateSelect);narrative.append(voiceControls,this.voiceStatus,html('p',{class:'transcript'},this.scene.narration||this.scene.explanation||'No narration has been authored.'));
  this.loadVoices=()=>{this.voices=('speechSynthesis'in window?window.speechSynthesis.getVoices():[]).filter(v=>v.localService);this.voiceToggle.disabled=!this.voices.length;this.voiceSelect.replaceChildren(...this.voices.map((v,i)=>html('option',{value:i},v.name+' · '+v.lang)));this.voiceStatus.textContent=this.voices.length?'Uses installed voices; no audio is sent to a service.':'No installed voice is available. The transcript remains readable.';};this.loadVoices();if('speechSynthesis'in window)window.speechSynthesis.addEventListener('voiceschanged',this.loadVoices);details.append(narrative);this.root.append(details);
  this.error=html('p',{class:'inline-error',role:'alert',hidden:''});this.root.append(this.error);
  stage.onkeydown=e=>{if(e.target!==stage)return;if(e.key===' '){e.preventDefault();this.playing?this.pause():this.play();}else if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();this.step(e.key==='ArrowRight'?1:-1);}else if(e.key==='Home'||e.key==='End'){e.preventDefault();this.pause();this.setTime(e.key==='Home'?0:1);}};
  this.visibility=()=>{if(document.hidden)this.pause();};document.addEventListener('visibilitychange',this.visibility);
 }
 setControl(id,v,render=true){const c=(this.scene.controls||[]).find(x=>x.id===id);if(!c)return;this.controls[id]=this.coerce(c,v);const ui=this.inputs.get(id);if(ui){ui.out.value=fmt(this.controls[id]);if(c.type==='toggle')ui.input.checked=!!this.controls[id];else ui.input.value=String(this.controls[id]);}if(render){this.render();this.notify(true);}}
 activate(o){this.pause();if(o.control_bind)this.setControl(o.control_bind.control_id,o.control_bind.value);if(o.reveal){this.reveal.hidden=false;this.reveal.replaceChildren(html('h3',{},o.reveal.title||o.label||o.id),html('p',{},o.reveal.text));if(o.reveal.block_id){const b=html('button',{type:'button',class:'text-button'},'Show the source ↗');b.onclick=()=>this.onSource(o.reveal.block_id);this.reveal.append(b);}}}
 vars(){const vars=Object.assign(Object.create(null),this.controls,{t:this.time});for(const[k,v]of Object.entries(this.scene.variables||{})){if(k==='t'||Object.hasOwn(this.controls,k))throw new Error('Duplicate scene variable: '+k);vars[k]=evaluate(v,vars);}return vars;}
 resolved(object,vars){const result={...object},props={};for(const k of this.scene.visual?.keyframes||[]){if(k.object_id!==object.id)continue;for(const[name,v]of Object.entries(k.props||{}))(props[name]??=[]).push({time:k.time,v});}for(const[name,frames]of Object.entries(props)){frames.sort((a,b)=>a.time-b.time);const before=[...frames].reverse().find(f=>f.time<=this.time),after=frames.find(f=>f.time>=this.time);if(!before){result[name]=after.v;continue;}if(!after||before.time===after.time){result[name]=before.v;continue;}const mix=(this.time-before.time)/(after.time-before.time);result[name]=val(before.v,vars)+(val(after.v,vars)-val(before.v,vars))*mix;}return result;}
 renderObject(raw,vars){
  const o=this.resolved(raw,vars),v=(key,f)=>val(o[key],vars,f),style={fill:o.fill||'none',stroke:o.stroke||'none','stroke-width':v('stroke_width',2),opacity:v('opacity',1)};let node;
  const arrow=(x1,y1,x2,y2)=>{const g=svg('g'),a=Math.atan2(y2-y1,x2-x1),s=9;g.append(svg('line',{...style,x1,y1,x2,y2}),svg('path',{...style,d:'M'+(x2-s*Math.cos(a-.45))+','+(y2-s*Math.sin(a-.45))+' L'+x2+','+y2+' L'+(x2-s*Math.cos(a+.45))+','+(y2-s*Math.sin(a+.45))}));return g;};
  switch(o.type){
   case'text':node=svg('text',{x:v('x'),y:v('y'),fill:o.fill||'#f1eee6','font-size':v('font_size',20),'font-family':'system-ui,sans-serif','text-anchor':o.align||'start',opacity:style.opacity},tpl(o.text,vars));break;
   case'rect':node=svg('rect',{...style,x:v('x'),y:v('y'),width:Math.max(0,v('width')),height:Math.max(0,v('height')),rx:v('rx',8)});break;
   case'circle':node=svg('circle',{...style,cx:v('cx'),cy:v('cy'),r:Math.max(0,v('r'))});break;
   case'line':node=svg('line',{...style,x1:v('x1'),y1:v('y1'),x2:v('x2'),y2:v('y2')});break;
   case'arrow':node=arrow(v('x1'),v('y1'),v('x2'),v('y2'));break;
   case'vector':{const x=v('x'),y=v('y'),dx=v('dx')*v('scale',1),dy=v('dy')*v('scale',1);node=arrow(x,y,x+dx,y-dy);if(o.label)node.append(svg('text',{x:x+dx+12,y:y-dy-8,fill:o.stroke||'#9ad8eb','font-size':16},tpl(o.label,vars)));break;}
   case'path':node=svg('path',{...style,d:String(o.d||'')});break;
   case'plot':{node=svg('g');const x=v('x'),y=v('y'),w=v('width',600),h=v('height',240),xmin=v('x_min',0),xmax=v('x_max',1),ymin=v('y_min',0),ymax=v('y_max',1),n=Math.max(8,Math.min(512,v('samples',100)));if(xmax===xmin||ymax===ymin)throw new Error('A plot axis has no range.');node.append(svg('rect',{x,y,width:w,height:h,fill:'none',stroke:'#36424b','stroke-width':1}));for(let j=1;j<4;j++)node.append(svg('line',{x1:x,y1:y+h*j/4,x2:x+w,y2:y+h*j/4,stroke:'#222d37','stroke-width':1}));let d='';for(let i=0;i<=n;i++){const vx=xmin+(xmax-xmin)*i/n,vy=evaluate(o.expr,{...vars,x:vx}),px=x+w*i/n,py=y+h-h*(vy-ymin)/(ymax-ymin);d+=(i?'L':'M')+px+','+Math.max(y-1000,Math.min(y+h+1000,py))+' ';}node.append(svg('path',{...style,fill:'none',stroke:o.stroke||'#9ad8eb',d}));break;}
   case'bars':{node=svg('g');const x=v('x'),y=v('y'),w=v('width',600),h=v('height',240),values=(o.values||[]).map(n=>evaluate(n,vars)),max=o.max===undefined?Math.max(1,...values.map(Math.abs)):v('max',1);if(max<=0)throw new Error('A bar scale must be positive.');const gap=w/Math.max(1,values.length),bw=gap*.66;values.forEach((n,i)=>{const bh=h*n/max;node.append(svg('rect',{x:x+i*gap+(gap-bw)/2,y:n>=0?y+h-bh:y+h,width:bw,height:Math.abs(bh),rx:3,fill:o.fill||'#9ad8eb',opacity:style.opacity}));node.append(svg('text',{x:x+i*gap+gap/2,y:y+h+24,'text-anchor':'middle',fill:'#bac7ce','font-size':13},o.labels?.[i]??String(i+1)));node.append(svg('text',{x:x+i*gap+gap/2,y:n>=0?y+h-bh-10:y+h+Math.abs(bh)+18,'text-anchor':'middle',fill:'#f1eee6','font-size':14},fmt(n)));});break;}
   case'matrix':{node=svg('g');const values=(o.values||[]).map(row=>row.map(n=>evaluate(n,vars))),rows=values.length,cols=values[0]?.length||0;if(!rows||!cols)throw new Error('A matrix needs values.');const x=v('x'),y=v('y'),cw=v('width',360)/cols,ch=v('height',240)/rows,lo=v('min',Math.min(...values.flat())),hi=v('max',Math.max(...values.flat())),ar=v('active_row',-1),ac=v('active_col',-1);values.forEach((row,r)=>row.forEach((n,c)=>{const strength=hi===lo?.5:clamp((n-lo)/(hi-lo)),focus=(ar<0||r===ar)&&(ac<0||c===ac);node.append(svg('rect',{x:x+c*cw+2,y:y+r*ch+2,width:Math.max(0,cw-4),height:Math.max(0,ch-4),rx:3,fill:o.fill||'#9ad8eb','fill-opacity':.08+.65*strength,stroke:focus&&(ar>=0||ac>=0)?'#efd4a3':o.stroke||'#34414a','stroke-width':focus&&(ar>=0||ac>=0)?2:1,opacity:style.opacity*(focus?1:.5)}));if(o.show_values!==false)node.append(svg('text',{x:x+(c+.5)*cw,y:y+(r+.5)*ch+5,'text-anchor':'middle',fill:'#f6f1e7','font-size':Math.min(16,ch*.3,cw*.23)},fmt(n)));}));for(let r=0;r<rows;r++)if(o.row_labels?.[r])node.append(svg('text',{x:x-10,y:y+(r+.5)*ch+5,'text-anchor':'end',fill:'#b9c6ce','font-size':13},o.row_labels[r]));for(let c=0;c<cols;c++)if(o.column_labels?.[c])node.append(svg('text',{x:x+(c+.5)*cw,y:y-14,'text-anchor':'middle',fill:'#b9c6ce','font-size':13},o.column_labels[c]));break;}
   default:throw new Error('Unsupported scene object: '+o.type);
  }
  node.setAttribute('data-object',o.id||'');if(o.reveal||o.control_bind){node.classList.add('interactive-object');node.style.cursor='pointer';node.addEventListener('click',()=>this.activate(o));node.append(svg('title',{},o.reveal?.title||o.label||o.id));}return node;
 }
 render(){if(this.destroyed)return;try{const vars=this.vars();this.drawing.replaceChildren(...(this.scene.visual?.objects||[]).map(o=>this.renderObject(o,vars)));const values=[];for(const o of this.scene.visual?.objects||[]){if(o.type==='text'&&String(o.text||'').includes('{{'))values.push(html('p',{},tpl(o.text,vars)));if(o.type==='bars')(o.values||[]).forEach((v,i)=>values.push(html('p',{},(o.labels?.[i]||'Value '+(i+1))+': '+fmt(evaluate(v,vars)))));if(o.type==='matrix')values.push(html('p',{},(o.label||o.id)+': '+o.values.map(row=>row.map(n=>fmt(evaluate(n,vars))).join(', ')).join(' / ')));}this.readouts.replaceChildren(...values);this.error.hidden=true;}catch(e){this.error.hidden=false;this.error.textContent=e.message;this.pause();}this.range.value=Math.round(this.time*1000);this.range.setAttribute('aria-valuetext',Math.round(this.time*100)+' percent');const seconds=Math.round(this.time*(this.scene.duration||12));this.position.value=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');this.playButton.textContent=this.playing?'Pause':this.reduced?'Advance':'Play';this.playButton.setAttribute('aria-label',this.playing?'Pause animation':this.reduced?'Advance to the next explanatory state':'Play animation');const i=this.steps.reduce((last,s,j)=>s.time<=this.time?j:last,-1);if(i!==this.currentStep){this.currentStep=i;this.caption.replaceChildren();if(i>=0)this.caption.append(html('span',{class:'step-index'},String(i+1).padStart(2,'0')),html('div',{},''));if(i>=0)this.caption.lastChild.append(html('strong',{},this.steps[i].title||'Step '+(i+1)),html('p',{},this.steps[i].text||''));}this.notify();}
 setTime(t){this.time=clamp(t);this.render();this.notify(true);}
 play(){if(this.playing)return;if(this.reduced&&!this.voiceToggle.checked){this.step(1);return;}if(this.time>=.999)this.time=0;this.playing=true;const text=this.scene.narration||this.scene.explanation;if(this.voiceToggle.checked&&this.voices.length&&text){this.time=0;const utterance=new SpeechSynthesisUtterance(text);utterance.voice=this.voices[Number(this.voiceSelect.value)]||this.voices[0];utterance.rate=Number(this.rateSelect.value);this.utterance=utterance;const start=performance.now(),estimate=Math.max(this.scene.duration||12,text.split(/\s+/).length/(2.5*utterance.rate));let lastBoundary=0;utterance.onboundary=e=>{if(e.charIndex>lastBoundary){lastBoundary=e.charIndex;const progress=clamp(e.charIndex/text.length);this.time=this.reduced?this.steps.reduce((last,step)=>step.time<=progress?step.time:last,0):progress;this.render();}};utterance.onend=()=>{this.time=1;this.pause();this.render();};utterance.onerror=e=>{if(e.error!=='canceled'&&e.error!=='interrupted'){this.voiceStatus.textContent='Narration could not start. Use the transcript or play without narration.';this.pause();}};window.speechSynthesis.cancel();window.speechSynthesis.speak(utterance);const tick=()=>{if(!this.playing)return;if(!lastBoundary){const progress=Math.min(.95,(performance.now()-start)/(estimate*1000));this.time=this.reduced?this.steps.reduce((last,step)=>step.time<=progress?step.time:last,0):progress;this.render();}this.frame=requestAnimationFrame(tick);};this.frame=requestAnimationFrame(tick);return;}const start=performance.now(),initial=this.time,duration=Math.max(1,this.scene.duration||12)*1000;const tick=()=>{if(!this.playing)return;this.time=clamp(initial+(performance.now()-start)/duration);this.render();if(this.time>=1){this.pause();return;}this.frame=requestAnimationFrame(tick);};this.frame=requestAnimationFrame(tick);}
 pause(){this.playing=false;cancelAnimationFrame(this.frame);if(this.utterance&&'speechSynthesis'in window){this.utterance.onend=null;window.speechSynthesis.cancel();this.utterance=null;}if(this.playButton)this.playButton.textContent=this.reduced?'Advance':'Play';this.notify(true);}
 step(dir){this.pause();const points=[...new Set([0,...this.steps.map(s=>s.time),...(this.scene.visual?.keyframes||[]).map(k=>k.time),1])].sort((a,b)=>a-b),t=dir>0?points.find(p=>p>this.time+.001):[...points].reverse().find(p=>p<this.time-.001);this.setTime(t??(dir>0?1:0));}
 state(){return{scene_id:this.scene.id,time:this.time,parameters:{...this.controls}};}
 notify(force=false){if(!this.destroyed&&(force||performance.now()-this.lastNotify>700)){this.lastNotify=performance.now();this.onChange(this.state());}}
 destroy(){this.pause();this.destroyed=true;document.removeEventListener('visibilitychange',this.visibility);if('speechSynthesis'in window)window.speechSynthesis.removeEventListener('voiceschanged',this.loadVoices);}
}
